### ISSUE TITLE
Milky

### ISSUE THREAD

**Issue by nokosage** [milkytiptoe/Name-Sync#49]
Ping.

Milky, are you dead? You have been unresponsive on every other medium for a very long time now. Respond immediately.

**Comment by lolligag9** [comment]
Very unsettling...

**Comment by nokosage** [comment]
Okay, so a week and no response, I now implemented https://namesync.net/ . It is on the same server it has always been. I had to make a new Chrome Store page because Milky has exclusive access to that, as well as the Opera page. Still waiting on Milky, but some changes needed to be made.

**Comment by ihavenoface** [comment]
I still have access to the Chrome Store page for what it's worth.

**Comment by nokosage** [comment]
Would you mind keeping the Chrome Store page up-to-date? I could notify you whenever it needs updating. I really do not like having to make a new Chrome Store page for it... it complicates things.

**Comment by ihavenoface** [comment]
Just checked some oldish backups and it seems like I've misplaced the cert that's needed to sign the addon. I presume there is no way to get around signing it before pushing an update?

**Comment by nokosage** [comment]
Unfortunately, I think you are right. Milky did respond to me earlier, so that is good; maybe you can get the private key from him?
